### ISSUE TITLE
Не запускается проект

### ISSUE THREAD

**Issue by MMAF22** [Renderhauer/BeeLoadMock#1]
Сбилдил с помощью команды: go build
Запускал с помощью команды: go run main.go
Проект не стартует в консоли ошибки:
![баг](https://github.com/Renderhauer/BeeLoadMock/assets/80857772/27cfe4d5-3f67-4dd9-bdd8-2d46f504e445)
Чего может не хватать для запуска, в readme не нашёл доп. инфу для запуска.

**Comment by MMAF22** [comment]
Разобрался, в readme не достаточно очевидно написано про запуск exe файла
Я подумал что надо заранить main.go.
Сам файл для запуска называется не очевидно m.exe

**Comment by Renderhauer** [comment]
Называется действительно не очевидно, но все же go - компилируемый ЯП, а значит после go build надо искать исполняемый файл, коими в винде являются .exe
Обновил ридми
